{
  "NServiceBus.MessageId": "632dc07d-2fa4-4735-85e6-a87e00a4b35b",
  "NServiceBus.MessageIntent": "Send",
  "NServiceBus.ReplyToAddress": "ClientUI",
  "NServiceBus.CorrelationId": "632dc07d-2fa4-4735-85e6-a87e00a4b35b",
  "NServiceBus.OriginatingMachine": "RALTSEVICHE",
  "NServiceBus.OriginatingEndpoint": "ClientUI",
  "$.diagnostics.originating.hostid": "d191d4af9f1f1c6626007b89f9a21e25",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "NewsPortal.MessagesNewsToElastic.RemoveCategoryCommand, NewsPortal.MessagesNewsToElastic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.ConversationId": "24ea48bf-49c4-4968-9ab1-a87e00a4b35b",
  "NServiceBus.Version": "6.4.3",
  "NServiceBus.TimeSent": "2018-02-05 09:59:39:396108 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "ElasticsearchCRUD.ElasticsearchCrudException",
  "NServiceBus.Retries.Timestamp": "2018-02-05 10:00:14:522436 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "Delete failed for item: categoryforelastics, categoryforelastic, 20  :",
  "NServiceBus.ExceptionInfo.Source": "ElasticsearchCrud",
  "NServiceBus.ExceptionInfo.StackTrace": "ElasticsearchCRUD.ElasticsearchCrudException: Delete failed for item: categoryforelastics, categoryforelastic, 20  :\u000d\u000a   at ElasticsearchCRUD.Utils.SyncExecute.<ExecuteResultDetails>b__3_1[T](Exception x)\u000d\u000a   at System.AggregateException.Handle(Func`2 predicate)\u000d\u000a   at ElasticsearchCRUD.Utils.SyncExecute.ExecuteResultDetails[T](Func`1 method)\u000d\u000a   at ElasticsearchCRUD.ContextAddDeleteUpdate.ElasticsearchContextAddDeleteUpdate.SaveChanges(List`1 entityPendingChanges, Boolean saveChangesAndInitMappingsForChildDocuments)\u000d\u000a   at ElasticsearchCRUD.ElasticsearchContext.SaveChanges()\u000d\u000a   at NewsPortal.EndPointUpdateElastic.CategoryDeleteHandler.Handle(RemoveCategoryCommand message, IMessageHandlerContext context)\u000d\u000a   at lambda_method(Closure , Object , Object , IMessageHandlerContext )\u000d\u000a   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)\u000d\u000a   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)\u000d\u000a   at NServiceBus.Pipeline.PipelineTerminator`1.Invoke(T context, Func`2 next)\u000d\u000a   at lambda_method(Closure , IInvokeHandlerContext )\u000d\u000a   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\u000d\u000a   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext()",
  "NServiceBus.TimeOfFailure": "2018-02-05 10:00:45:602508 Z",
  "NServiceBus.FailedQ": "UpdateElastic",
  "NServiceBus.ProcessingMachine": "RALTSEVICHE",
  "NServiceBus.ProcessingEndpoint": "UpdateElastic",
  "$.diagnostics.hostid": "42b6e8f82fa2fac41c63cd9a473c05f7",
  "$.diagnostics.hostdisplayname": "RALTSEVICHE"
}